### PR TITLE
Added Scores form tab for documents

### LINKED ISSUE #2: Create "Scores" tab on the document page with multiple fields for score input
Potential Fields to Score on:
- Transcript/GPA
- Skills
- Essay
- Interview
- Match with college

### PR DESCRIPTION
**Pull request by hiVictoria**
Added 'Scores' tab to document with a form where reviewers can input scores (0-5) for Skills, Experience, Transcript & GPA, and Match with College. Resolves #2 

image

### CODE REVIEW

**Review by claralam — COMMENTED** [review]
If it's possible, I think it might be easier if the scores were saved as integers! That way, if we aggregate them later in the dashboard, it'll be easier.

Also, are you thinking of adding a submit/save button for the form?

**Comment by hiVictoria** [comment]
Sounds good! I think for option inputs, they will be passed as strings and we will have to convert them to integers in the backend. We can come back to it later if needed. But yes I will definitely add the save button!

**Review by claralam — COMMENTED** [review]
I think there might be some extra spacing to the left of the button that is making it not line up with the form. Other than that, I think the form looks good!

**Comment by claralam** [comment]
Looked good to me! Forgot to mark as "Approved" before merging.

**Pull request merged**
